name: Django Tests

on:
  push:
    branches:
      -main
      -master

  pull_request:
    branches:
      -main
      -master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.11
      uses: action/setup-python@v2
      with:
        python-version: 3.7
    - name: Install all the dependencies
      run:
        python -m pip install --upgrade
        pip install -r requirements.txt
    - name: Lint with flake8
      run:
        pip install flake8
        flake8
    - name: Coverage report
      run:
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django testing
      run:
        python3 manage.py test